trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Set up Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm test
    displayName: 'Run tests'

  - script: |
      npm run build
    displayName: 'Build the project'

  - script: |
      npx azure-static-web-apps-cli deploy --api-token $(STATIC_WEB_APPS_API_TOKEN)
    displayName: 'Deploy to Azure Static Web Apps'
    env:
      STATIC_WEB_APPS_API_TOKEN: $(STATIC_WEB_APPS_API_TOKEN)
